Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2024-07, with the labels that each got.

#266 French translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-es/strings.xml
  app/src/commonMain/composeResources/values-fr/strings.xml
Labels: translations

#267 Add icons to the settings tab for better readability
  app/src/commonMain/kotlin/ui/SettingsScreen.kt
Labels: feature

#268 Spanish translations added from Hosted Weblate
  app/src/commonMain/composeResources/values-es/strings.xml
Labels: translations

#270 Update German translations
  app/src/commonMain/composeResources/values-de/strings.xml
Labels: translations

#271 Remove duplicate string
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values-es/strings.xml
  app/src/commonMain/composeResources/values-fr/strings.xml
  app/src/commonMain/composeResources/values-hi/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
Labels: cleanup / restructuring

#275 Translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-fr/strings.xml
  app/src/commonMain/composeResources/values-hi/strings.xml
Labels: translations

#276 Fix bug wrong date calculation
  app/src/commonMain/kotlin/Extensions.kt
  app/src/commonMain/kotlin/model/DateTimeCalculator.kt
  app/src/commonMain/kotlin/ui/editexpense/FirstPaymentOption.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/commonTest/kotlin/model/DateTimeCalculatorTest.kt
  app/src/commonTest/kotlin/model/database/RecurringExpenseTest.kt
Labels: bug

#273 Define a currency per expense
  .github/scripts/update_exchange_rates.py
  .github/workflows/release.yml
  app/schemas/model.database.RecurringExpenseDatabase/6.json
  app/src/androidMain/kotlin/model/SystemCurrencyProvider.android.kt
  app/src/commonMain/composeResources/files/currencies.json
  app/src/commonMain/composeResources/files/exchange_rates.json
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/data/CurrencyOption.kt
  app/src/commonMain/kotlin/data/CurrencyValue.kt
  app/src/commonMain/kotlin/data/RecurringExpenseData.kt
  app/src/commonMain/kotlin/data/UpcomingPaymentData.kt
  app/src/commonMain/kotlin/di/Module.kt
  app/src/commonMain/kotlin/model/ExchangeRateProvider.kt
  app/src/commonMain/kotlin/model/SystemCurrencyProvider.kt
  app/src/commonMain/kotlin/model/database/RecurringExpense.kt
  app/src/commonMain/kotlin/model/database/RecurringExpenseDatabase.kt
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/SettingsScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/EditRecurringExpenseScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/PriceOption.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  app/src/commonMain/kotlin/viewmodel/EditRecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseConverter.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/commonTest/kotlin/model/database/RecurringExpenseTest.kt
  app/src/desktopMain/kotlin/model/SystemCurrencyProvider.desktop.kt
  app/src/iosMain/kotlin/model/SystemCurrencyProvider.ios.kt
Labels: feature

#289 Fix date formatting in upcoming payments screen
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
Labels: bug
