Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2024-10, with the labels that each got.

#353 Added (Chinese (Traditional Han script)) translation using Weblate
  app/src/commonMain/composeResources/values-zh-rTW/strings.xml
Labels: translations

#354 Update ksp to match Kotlin version
  .github/renovate.json
  gradle/libs.versions.toml
Labels: dependencies

#355 Update Compose Plugin to 1.7.0
  app/src/commonMain/kotlin/ui/editexpense/PriceOption.kt
  app/src/commonMain/kotlin/ui/editexpense/RecurrenceOption.kt
  gradle/libs.versions.toml
Labels: dependencies

#356 Update exchange rates
  app/src/commonMain/composeResources/files/exchange_rates.json
Labels: dependencies

#360 Remove obsolete disableCompilerDaemon flag
  gradle.properties
Labels: cleanup / restructuring
