Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2024-08, with the labels that each got.

#291 Update Spanish translations
  app/src/commonMain/composeResources/values-es/strings.xml
Labels: translations

#292 Translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-hi/strings.xml
Labels: translations

#306 Fix wrong currency on upcoming tab
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
Labels: bug

#307 Make release tags builds are reproducible again
  .github/workflows/release.yml
  .github/workflows/trigger_new_release.yml
Labels: bug

#308 Remove obsolete enableStrongSkippingMode declaration
  app/build.gradle.kts
Labels: cleanup / restructuring
