Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2024-11, with the labels that each got.

#368 Update exchange rates
  app/src/commonMain/composeResources/files/exchange_rates.json
Labels: dependencies

#376 Adjust manifest targetApi define to fix warning
  app/src/androidMain/AndroidManifest.xml
Labels: cleanup / restructuring

#377 Added Russian translations using Weblate
  app/src/commonMain/composeResources/values-ru/strings.xml
Labels: translations

#378 Update JVM from 17 to 21
  .github/workflows/pr_pipeline.yml
  .github/workflows/release.yml
  app/build.gradle.kts
Labels: dependencies

#380 Update Kotlin to 2.1.0
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#383 Update to Android 15 (sdk version 35)
  .github/workflows/release.yml
  gradle/libs.versions.toml
Labels: dependencies
