Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-02, with the labels that each got.

#416 Translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-ta/strings.xml
Labels: translations

#419 Update KSP to 2.1.10-1.0.29
  gradle/libs.versions.toml
Labels: dependencies

#425 Add upcoming expense notifications
  app/build.gradle.kts
  app/schemas/model.database.RecurringExpenseDatabase/7.json
  app/src/androidMain/AndroidManifest.xml
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/androidMain/kotlin/di/Module.android.kt
  app/src/androidMain/kotlin/model/notification/AlarmLoopReceiver.kt
  app/src/androidMain/kotlin/model/notification/DismissExpenseNotificationReceiver.kt
  app/src/androidMain/kotlin/model/notification/NotificationLoopReceiver.kt
  app/src/androidMain/kotlin/model/notification/SystemNotificationBuilder.kt
  app/src/androidMain/res/drawable/ic_notification_icon.xml
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/data/RecurringExpenseData.kt
  app/src/commonMain/kotlin/di/Module.kt
  app/src/commonMain/kotlin/model/database/RecurringExpense.kt
  app/src/commonMain/kotlin/model/database/RecurringExpenseDatabase.kt
  app/src/commonMain/kotlin/model/database/UserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/notification/ExpenseNotificationManager.kt
  app/src/commonMain/kotlin/model/notification/NotificationData.kt
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/SettingsScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/EditRecurringExpenseScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/NotificationOption.kt
  app/src/commonMain/kotlin/ui/editexpense/RecurrenceOption.kt
  app/src/commonMain/kotlin/ui/elements/TimePickerDialog.kt
  app/src/commonMain/kotlin/viewmodel/EditRecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseConverter.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/commonTest/kotlin/model/database/RecurringExpenseTest.kt
  app/src/desktopMain/kotlin/Main.kt
  app/src/iosMain/kotlin/MainViewController.kt
  gradle/libs.versions.toml
Labels: feature

#429 Fix compile breaks building the iOS version
  app/src/iosMain/kotlin/MainViewController.kt
  gradle.properties
  gradle/libs.versions.toml
  iosApp/iosApp/iOSApp.swift
Labels: cleanup / restructuring

#428 Indonesian Translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-in/strings.xml
Labels: translations

#434 Hide notification setting in edit screen
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/editexpense/EditRecurringExpenseScreen.kt
Labels: bug

#435 Translations update from Hosted Weblate
  app/src/commonMain/composeResources/values-in/strings.xml
  app/src/commonMain/composeResources/values-ru/strings.xml
Labels: translations
