Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-04, with the labels that each got.

#462 Make currency dropdown searchable
  app/src/commonMain/kotlin/data/CurrencyOption.kt
  app/src/commonMain/kotlin/ui/editexpense/EditRecurringExpenseScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/PriceOption.kt
  app/src/commonMain/kotlin/viewmodel/EditRecurringExpenseViewModel.kt
Labels: feature

#474 Only export the licenses of release dependencies
  app/build.gradle.kts
Labels: bug

#476 Migrate to a single scaffold in app
  app/src/commonMain/kotlin/di/Module.kt
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/SettingsScreen.kt
  app/src/commonMain/kotlin/ui/about/AboutLibrariesScreen.kt
  app/src/commonMain/kotlin/ui/about/AboutScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/EditRecurringExpenseScreen.kt
  app/src/commonMain/kotlin/ui/editexpense/NotificationOption.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  app/src/commonMain/kotlin/viewmodel/MainNavigationViewModel.kt
Labels: cleanup / restructuring

#479 Create separate screen for default currency selection
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/data/Navigation.kt
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/SettingsScreen.kt
  app/src/commonMain/kotlin/ui/settings/SettingsClickableElement.kt
  app/src/commonMain/kotlin/ui/settings/SettingsClickableElementWithToggle.kt
  app/src/commonMain/kotlin/ui/settings/SettingsDefaultCurrencyScreen.kt
  app/src/commonMain/kotlin/ui/settings/SettingsHeaderElement.kt
  app/src/commonMain/kotlin/ui/settings/SettingsMainScreen.kt
  app/src/commonMain/kotlin/ui/settings/SettingsMissingPermissionElement.kt
  app/src/commonMain/kotlin/ui/settings/SettingsScreen.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
Labels: feature

#480 Add option to switch back to system default currency
  app/src/commonMain/kotlin/ui/settings/SettingsDefaultCurrencyScreen.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
Labels: feature

#481 Add support for 170+ currencies
  .github/scripts/update_exchange_rates.py
  app/src/commonMain/composeResources/files/currencies.json
  app/src/commonMain/composeResources/files/exchange_rates.json
  app/src/commonMain/kotlin/model/CurrencyProvider.kt
  app/src/commonMain/kotlin/model/ExchangeRateProvider.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
Labels: feature
