Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-08, with the labels that each got.

#628 Only allow ksp versions without alpha, beta or rc
  .github/renovate.json
Labels: cleanup / restructuring

#638 (Spanish) translation updated
  app/src/commonMain/composeResources/values-es/strings.xml
Labels: translations

#650 Migrate to new KMP project structure
  app/build.gradle.kts
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/Extensions.desktop.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/Main.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/PlatformRequests.desktop.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/di/Module.desktop.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/model/SystemCurrencyProvider.desktop.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/model/database/GetDatabaseBuilder.kt
  app/src/jvmMain/kotlin/de/dbauer/expensetracker/ui/theme/Theme.jvm.kt
  gradle.properties
  settings.gradle.kts
Labels: cleanup / restructuring

#651 Add hot reload plugin
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: cleanup / restructuring

#661 Remove unused composable and update strings
  app/src/commonMain/composeResources/values-ar/strings.xml
  app/src/commonMain/composeResources/values-cs/strings.xml
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values-es/strings.xml
  app/src/commonMain/composeResources/values-fr/strings.xml
  app/src/commonMain/composeResources/values-hi/strings.xml
  app/src/commonMain/composeResources/values-in/strings.xml
  app/src/commonMain/composeResources/values-nl/strings.xml
  app/src/commonMain/composeResources/values-pl/strings.xml
  app/src/commonMain/composeResources/values-pt-rBR/strings.xml
  app/src/commonMain/composeResources/values-pt/strings.xml
  app/src/commonMain/composeResources/values-ru/strings.xml
  app/src/commonMain/composeResources/values-ta/strings.xml
  app/src/commonMain/composeResources/values-tr/strings.xml
  app/src/commonMain/composeResources/values-zh-rCN/strings.xml
  app/src/commonMain/composeResources/values-zh-rTW/strings.xml
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/editexpense/ColorOption.kt
Labels: cleanup / restructuring

#662 Add tags to Widget
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/UpcomingPaymentsWidget.kt
Labels: feature

#663 Disable Gradle cache, daemon and configuration cache for all pipelines
  .github/workflows/pr_pipeline.yml
  .github/workflows/release.yml
Labels: cleanup / restructuring

#664 Add further colors for tags
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/customizations/ExpenseColor.kt
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/customizations/TagColors.kt
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/tags/AddTagDialog.kt
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/theme/Color.kt
Labels: feature

#665 Allow adding fully custom colors to tags
  app/build.gradle.kts
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/tags/AddTagDialog.kt
  gradle/libs.versions.toml
Labels: feature

#666 (Arabic) translation updated
  app/src/commonMain/composeResources/values-ar/strings.xml
Labels: translations

#669 Fix flickering of assign tag animation
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/ComposeExtensions.kt
Labels: bug

#670 Adjust Whats New show condition
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/whatsnew/WhatsNew.kt
Labels: cleanup / restructuring

#671 Sort tags by title in overview
  app/src/commonMain/kotlin/de/dbauer/expensetracker/model/database/RecurringExpenseWithTagsMapper.kt
Labels: bug

#675 Add "Contribute an idea or report an issue" to settings
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/de/dbauer/expensetracker/ui/about/AboutScreen.kt
Labels: feature

#676 (Russian) translation updated
  app/src/commonMain/composeResources/values-ru/strings.xml
Labels: translations

#677 Use default token for AboutLibraries
  .github/workflows/release.yml
Labels: cleanup / restructuring

#685 Fix F-Droid reproducible builds by pre-generating libraries copyright file
  .github/workflows/prepare_next_release.yml
  .github/workflows/release.yml
  .github/workflows/update_currency_rates.yml
  app/build.gradle.kts
Labels: bug

#688 (German) translation updated
  app/src/commonMain/composeResources/values-de/strings.xml
Labels: translations

#689 (Polish) translation updated
  app/src/commonMain/composeResources/values-pl/strings.xml
Labels: translations
