Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-07, with the labels that each got.

#600 Update kotlinx-datetime to v0.7.1
  gradle/libs.versions.toml
Labels: dependencies

#602 Update currency pipeline
  .github/workflows/trigger_new_release.yml
  .github/workflows/update_currency_rates.yml
Labels: cleanup / restructuring

#616 Added (Polish) translation
  app/src/commonMain/composeResources/values-pl/strings.xml
Labels: translations
