Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-06, with the labels that each got.

#539 (French) and (Czech) translation updated using Weblate
  app/src/commonMain/composeResources/values-cs/strings.xml
  app/src/commonMain/composeResources/values-fr/strings.xml
Labels: translations

#546 Create UnitTests for UpcomingPaymentsViewModel
  app/build.gradle.kts
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/UpcomingPaymentsWidgetModel.kt
  app/src/commonMain/kotlin/Extensions.kt
  app/src/commonMain/kotlin/di/Module.kt
  app/src/commonMain/kotlin/model/DateTimeCalculator.kt
  app/src/commonMain/kotlin/model/ExchangeRateProvider.kt
  app/src/commonMain/kotlin/model/FakeExchangeRateProvider.kt
  app/src/commonMain/kotlin/model/IExchangeRateProvider.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/commonTest/kotlin/viewmodel/UpcomingPaymentsViewModelTest.kt
  gradle/libs.versions.toml
Labels: cleanup / restructuring

#548 Add widget preview (Android >= 15) and allow transparent background
  app/src/androidMain/kotlin/de/dbauer/expensetracker/ExpenseTrackerApplication.kt
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/ConfigureWidgetActivity.kt
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/UpcomingPaymentsWidget.kt
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/model/datastore/FakeUserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/datastore/IUserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/datastore/UserPreferencesRepository.kt
  gradle/libs.versions.toml
Labels: feature

#563 (Czech) translation updated using Weblate
  app/src/commonMain/composeResources/values-cs/strings.xml
Labels: translations

#569 Update Compose plugin to 1.8.2
  gradle/libs.versions.toml
Labels: dependencies

#581 exclude org.jetbrains.kotlinx from the Kotlin group
  .github/renovate.json
Labels: cleanup / restructuring

#588 Disable warning for unavailable targets on some platforms
  gradle.properties
Labels: cleanup / restructuring

#593 Fix iOS build
  app/src/iosMain/kotlin/Extensions.ios.kt
Labels: cleanup / restructuring

#579 Translations updated
  app/src/commonMain/composeResources/values-ar/strings.xml
  app/src/commonMain/composeResources/values-es/strings.xml
Labels: translations

#595 Make warnings fail as error
  app/build.gradle.kts
Labels: cleanup / restructuring
