Repository DennisBauer/RecurringExpenseTracker, pull requests merged in 2025-05, with the labels that each got.

#487 Fix warning - do not forward ViewModel between Composables
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
Labels: cleanup / restructuring

#489 Add setting to show original currency of expenses
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/model/database/UserPreferencesRepository.kt
  app/src/commonMain/kotlin/ui/settings/SettingsClickableElementWithToggle.kt
  app/src/commonMain/kotlin/ui/settings/SettingsMainScreen.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
Labels: feature

#490 Adjust expense font sizes and readjust Grid Layout
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
Labels: feature

#491 Move RecurringExpenseViewModel to respective Composable
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
Labels: cleanup / restructuring

#492 Make sure Coroutines can be debugged properly
  app/build.gradle.kts
Labels: cleanup / restructuring

#493 Add remaining expenses this month to upcoming payments screen
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
Labels: feature

#494 Overhaul Upcoming screen
  app/src/androidMain/kotlin/Extensions.android.kt
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/Extensions.kt
  app/src/commonMain/kotlin/model/database/RecurringExpense.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/desktopMain/kotlin/Extensions.desktop.kt
  app/src/iosMain/kotlin/Extensions.ios.kt
Labels: feature

#495 Add option to choose theme in settings
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/model/database/UserPreferencesRepository.kt
  app/src/commonMain/kotlin/ui/ThemeMode.kt
  app/src/commonMain/kotlin/ui/settings/SettingsMainScreen.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
  app/src/iosMain/kotlin/MainViewController.kt
Labels: feature

#496 Make sure user theme is used everywhere when changed in settings
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/commonMain/kotlin/Extensions.kt
  app/src/commonMain/kotlin/ui/theme/Color.kt
Labels: bug

#497 Add setting to choose default tab opening on startup
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/commonMain/composeResources/values-de/strings.xml
  app/src/commonMain/composeResources/values/strings.xml
  app/src/commonMain/kotlin/model/database/UserPreferencesRepository.kt
  app/src/commonMain/kotlin/ui/DefaultTab.kt
  app/src/commonMain/kotlin/ui/settings/SettingsMainScreen.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
Labels: feature

#502 Update navigation to 2.9.0-alpha17 + Migrate to KClass navigation
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/androidMain/kotlin/model/notification/SystemNotificationBuilder.kt
  app/src/commonMain/kotlin/data/Navigation.kt
  app/src/commonMain/kotlin/ui/BottomNavBar.kt
  app/src/commonMain/kotlin/ui/MainContent.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/settings/SettingsScreen.kt
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  gradle/libs.versions.toml
Labels: dependencies

#503 Make use of theme switcher for Desktop platform
  app/src/desktopMain/kotlin/Main.kt
Labels: bug

#507 Update Compose Plugin to 1.8.0
  gradle/libs.versions.toml
Labels: dependencies

#510 Update KSP to 2.1.20-2.0.1
  gradle.properties
  gradle/libs.versions.toml
Labels: dependencies

#512 Enable compose preview support
  app/src/androidMain/kotlin/de/dbauer/expensetracker/MainActivity.kt
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/ConfigureWidgetActivity.kt
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/UpcomingPaymentsWidget.kt
  app/src/androidMain/kotlin/de/dbauer/expensetracker/widget/UpcomingPaymentsWidgetModel.kt
  app/src/androidMain/kotlin/di/Module.android.kt
  app/src/androidMain/kotlin/model/notification/NotificationLoopReceiver.kt
  app/src/commonMain/kotlin/Extensions.kt
  app/src/commonMain/kotlin/di/Module.kt
  app/src/commonMain/kotlin/model/datastore/FakeUserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/datastore/IUserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/datastore/UserPreferencesRepository.kt
  app/src/commonMain/kotlin/model/notification/ExpenseNotificationManager.kt
  app/src/commonMain/kotlin/ui/RecurringExpenseOverview.kt
  app/src/commonMain/kotlin/ui/editexpense/ColorOption.kt
  app/src/commonMain/kotlin/ui/theme/PreviewTheme.kt
  app/src/commonMain/kotlin/viewmodel/EditRecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/RecurringExpenseViewModel.kt
  app/src/commonMain/kotlin/viewmodel/SettingsViewModel.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
  app/src/desktopMain/kotlin/Main.kt
  app/src/desktopMain/kotlin/di/Module.desktop.kt
  app/src/iosMain/kotlin/MainViewController.kt
  app/src/iosMain/kotlin/di/Module.ios.kt
Labels: cleanup / restructuring

#514 Added (Turkish) translation + update (Russian) translation using Weblate
  app/src/commonMain/composeResources/values-ru/strings.xml
  app/src/commonMain/composeResources/values-tr/strings.xml
Labels: translations

#517 Update Gradle to 8.12.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#518 Update ksp to 2.1.21-2.0.1
  gradle/libs.versions.toml
Labels: dependencies

#519 Fix ksp configuration warning
  app/build.gradle.kts
Labels: cleanup / restructuring

#521 Remove duplicated EditRecurringExpenseViewModel in previewModule
  app/src/commonMain/kotlin/di/Module.kt
Labels: cleanup / restructuring

#522 Fix a bug where upcoming expenses were only listed once each month
  app/src/commonMain/kotlin/ui/upcomingexpenses/UpcomingPaymentsScreen.kt
  app/src/commonMain/kotlin/viewmodel/UpcomingPaymentsViewModel.kt
Labels: bug

#531 Attempt to make Renovate update KSP properly
  .github/renovate.json
Labels: cleanup / restructuring

#532 Update Compose Plugin to 1.8.1
  gradle/libs.versions.toml
Labels: dependencies

#533 Migrate Renovate config
  .github/renovate.json
Labels: cleanup / restructuring

#536 Remove Renovate configMigration
  .github/renovate.json
Labels: cleanup / restructuring

#538 Update (French) and (Czech) translation from Hosted Weblate
  app/src/commonMain/composeResources/values-cs/strings.xml
  app/src/commonMain/composeResources/values-fr/strings.xml
Labels: translations
